name: SMA Easy MQTT (SBFspot)
slug: sma_easy_mqtt
version: "0.1.0"
description: Publish SMA inverter data locally to MQTT via SBFspot (no cloud)
arch: [aarch64, amd64]
startup: services
boot: auto
host_network: true
init: false
map:
  - config:rw

options:
  inverter_ip: "192.168.1.100"
  inverter_user_password: "0000"
  plant_name: "MyPlant"
  mqtt_host: "homeassistant"
  mqtt_port: 1883
  mqtt_username: "sbfspot"
  mqtt_password: ""
  mqtt_topic: "sbfspot/{plantname}/{serial}"
  interval_seconds: 30

schema:
  inverter_ip:
    type: string
    required: true
    pattern: '^([0-9]{1,3}\.){3}[0-9]{1,3}$'
  inverter_user_password:
    type: string
    required: true
    password: true
  plant_name: str
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password:
    type: string
    password: true
  mqtt_topic:
    type: string
    required: true
  interval_seconds: int
